name: Test pull_request_target

on:
  pull_request_target:
    branches:
      - main
      - origin

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event name
        run: echo "Event: ${{ github.event_name }}"
